name = "rollshow"
main = "worker.js"
compatibility_date = "2024-01-01"

assets = { directory = "./public" }

# ============================================================
# D1 DATABASE
# ============================================================
[[d1_databases]]
binding = "DB_users"
database_name = "roll_show"
database_id = "0d166ea1-00fb-4701-bf43-fe2a652b7ce2"

# ============================================================
# R2 BUCKET FOR REAL MEDIA (MUSIC, VIDEO, PHOTOS)
# ============================================================
[[r2_buckets]]
binding = "R2"
bucket_name = "rollshow"
preview_bucket_name = "rollshow"

# ============================================================
# KV NAMESPACE FOR METADATA + CACHING
# ============================================================
[[kv_namespaces]]
binding = "KV"
id = "94027daf38234d6a914cfd48c91e55f3"
preview_id = "94027daf38234d6a914cfd48c91e55f3"

# ============================================================
# SERVICE BINDING TO AUTH WORKER
# ============================================================
[[services]]
binding = "AUTH"
service = "rollshow-auth"

[observability]
enabled = false

[observability.logs]
invocation_logs = true
