name = "roll-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# Serve your frontend from /app (Worker mode)
assets = { directory = "./app" }

# Required when using assets in Worker mode
routes = [
  { pattern = "roll-show.pages.dev/*", zone_name = "pages.dev" }
]

# Bind your D1 database
[[d1_databases]]
binding = "DB"
database_name = "roll_show"
database_id = "fe6c6c63-9a89-4dfc-ad2f-0d69c8365bf2"

# Observability
[observability]
enabled = false

[observability.logs]
invocation_logs = true
