DROP TABLE IF EXISTS skate_cards;

CREATE TABLE skate_cards (
  id TEXT PRIMARY KEY,                     -- card_id (UUID)
  skater_id TEXT NOT NULL,                 -- skater_profiles.id

  title TEXT NOT NULL,
  description TEXT,

  image_url TEXT,                          -- generated by branding tool
  rarity TEXT,                             -- common | rare | legendary | 1-of-1
  edition_size INTEGER,                    -- total minted
  price_cents INTEGER,                     -- optional price

  card_type TEXT DEFAULT 'standard',       -- standard | show | campaign | merch | profile
  qr_code_url TEXT,                        -- auto-generated QR for sharing/selling

  created_at TEXT NOT NULL,

  FOREIGN KEY (skater_id) REFERENCES skater_profiles(id)
);
