name = "rollshow-auth"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB_users"
database_name = "DB_users"
database_id = "4688d694-1a33-4055-b2a4-6f5c2231a356"
